### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by ABHOODIES** [MohitSojitra/portfolio#1]
after running npm start & npm install the website show me this
![image](https://user-images.githubusercontent.com/104942135/167265393-987a9323-06b8-417b-a3c5-ddca75ea91dc.png)

and the console shows this error 
Failed to compile.

./src/components/About/Toolstack.js
Attempted import error: 'SiVercel' is not exported from 'react-icons/si'.

**Comment by MohitSojitra** [comment]
There is problem in react-icons package. But now its fix. Please check it.

Thanks for creating issue.
